pharma/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'pharma'

urlpatterns = [

    # /pharma/
    url(r'^$', views.index, name='index'),

    # /pharma/doctor/
    url(r'^doctor/$', views.doctor, name='doctor'),

# /pharma/doctor/
    url(r'^doctor/adddocs$', views.adddocs, name='adddocs'),

    # /pharma/doctor/
    url(r'^doctor/(?P<pk>[0-9]+)/deldocs$', views.deldocs, name='deldocs'),

    # /pharma/doctor/
    url(r'^doctor/(?P<pk>[0-9]+)/delmeds$', views.delmeds, name='delmeds'),

    # /pharma/doctor/
    url(r'^doctor/(?P<pk>[0-9]+)/delnonmeds', views.delnonmeds, name='delnonmeds'),

    # /pharma/doctor/
    url(r'^doctor/(?P<pk>[0-9]+)/delstaffs', views.delstaffs, name='delstaffs'),

    # /pharma/doctor/
    url(r'^doctor/adddocs/adddoc$', views.adddoc, name='adddoc'),

    # /pharma/doctor/
    url(r'^medicine/addmeds$', views.addmeds, name='addmeds'),

    # /pharma/doctor/
    url(r'^doctor/addmeds/addmed$', views.addmed, name='addmed'),

    # /pharma/doctor/
    url(r'^doctor/addnonmeds$', views.addnonmeds, name='addnonmeds'),

    # /pharma/doctor/
    url(r'^doctor/addnonmeds/addnonmed$', views.addnonmed, name='addnonmed'),

    # /pharma/doctor/
    url(r'^doctor/addstaffs$', views.addstaffs, name='addstaffs'),

    # /pharma/doctor/
    url(r'^doctor/addstaffs/addstaff$', views.addstaff, name='addstaff'),

    # /pharma/medicine/
    url(r'^medicine/$', views.medicine, name='medicine'),

    # /pharma/nonmedicine/
    url(r'^nonmedicine/$', views.nonmedicine, name='nonmedicine'),

    # /pharma/staff/
    url(r'^staff/$', views.staff, name='staff'),

    # /pharma/docs/Andheri
    url(r'^docs/(?P<site>[a-zA-Z]+)/$', views.dispdocs, name='dispdocs'),

    # /pharma/meds/Andheri
    url(r'^meds/(?P<site>[a-zA-Z]+)/$', views.dispmeds, name='dispmeds'),

    # /pharma/nonmeds/Andheri
    url(r'^nonmeds/(?P<site>[a-zA-Z]+)/$', views.dispnonmeds, name='dispnonmeds'),

    # /pharma/staff/Andheri
    url(r'^staff/(?P<site>[a-zA-Z]+)/$', views.dispstaff, name='dispstaff'),
# url(r'^staff/$', views.staff, name='staff'),

    url(r'^get_doctor/$', views.get_doctor),

    url(r'^get_medicine/$', views.get_medicine),

    url(r'^get_non_medicine/$', views.get_non_medicine),

    url(r'^get_staff/$', views.get_staff),

]

pharmacy/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.
from pharma import views




# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('pharma.urls'), name='index'),

]

pharma/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Staff(models.Model):
    name = models.CharField(max_length=1000)
    age = models.IntegerField()
    loc = models.CharField(max_length=1000)


    def __str__(self):
        return self.name

class Medicines(models.Model):
    name = models.CharField(max_length=1000)
    composition = models.CharField(max_length=1000)
    exp_date = models.DateField()
    manu_date = models.DateField()
    price = models.FloatField()
    quantity = models.IntegerField()


    def __str__(self):
        return self.name


class Nonmedicine(models.Model):
    name = models.CharField(max_length=1000)
    exp_date = models.DateField()
    manu_date = models.DateField()
    price = models.FloatField()
    quantity = models.IntegerField()

    def __str__(self):
        return self.name

class Doctor(models.Model):
    name = models.CharField(max_length=1000)
    qualification = models.CharField(max_length=1000)
    reg_no = models.IntegerField()
    pt_ref = models.IntegerField()


    def __str__(self):
        return self.name



class Location(models.Model):
    loc = models.CharField(max_length=50)
    ip = models.CharField(max_length=15)

    def __str__(self):
        return self.loc

pharma/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from pharma.models import Staff,Doctor,Medicines,Nonmedicine, Location
from django.forms.models import model_to_dict
import requests
from json import loads


# Create your views here.
def index(request):
    return render(request, 'pharma/home.html')


def doctor(request):
    doctors=Doctor.objects.all()
    context = {'doctors': doctors, 'site': 'Our'}
    print context
    return render(request,'pharma/doctor.html', context)


def medicine(request):
    medicines = Medicines.objects.all()
    context = {'medicines': medicines, 'site': 'Our'}
    return render(request, 'pharma/medicine.html', context)


def nonmedicine(request):
    nonmedicines = Nonmedicine.objects.all()
    context = {'nonmedicines': nonmedicines, 'site': 'Our'}
    return render(request, 'pharma/nonmedicine.html', context)


def staff(request):
    staffs = Staff.objects.all()
    context = {'staffs': staffs, 'site': 'Our'}
    return render(request, 'pharma/staff.html', context)


def dispdocs(request, site):
    location = get_object_or_404(Location, loc=site)
    url = "http://" + location.ip + ":8000/get_doctor/"
    req = requests.get(url)
    context = loads(req.text.decode('utf-8'))
    context['site'] = site
    print context
    return render(request, 'pharma/doctor.html', context)


def dispmeds(request, site):
    location = get_object_or_404(Location, loc=site)
    url = "http://" + location.ip + ":8000/get_medicine/"
    req = requests.get(url)
    context = loads(req.text.decode('utf-8'))
    context['site'] = site
    print context
    return render(request, 'pharma/medicine.html', context)


def dispnonmeds(request, site):
    location = get_object_or_404(Location, loc=site)
    url = "http://" + location.ip + ":8000/get_non_medicine/"
    req = requests.get(url)
    context = loads(req.text.decode('utf-8'))
    context['site'] = site
    print context
    return render(request, 'pharma/nonmedicine.html', context)


def dispstaff(request, site):
    location = get_object_or_404(Location, loc=site)
    url = "http://" + location.ip + ":8000/get_staff/"
    req = requests.get(url)
    context = loads(req.text.decode('utf-8'))
    context['site'] = site
    print context
    return render(request, 'pharma/staff.html', context)


def get_doctor(request):
    data_dict = dict()
    data_dict["doctors"] = list()
    for d in Doctor.objects.all():
        data_dict["doctors"].append(model_to_dict(d))
    return JsonResponse(data_dict)


def get_medicine(request):
    data_dict = dict()
    data_dict["medicines"] = list()
    for m in Medicines.objects.all():
        data_dict["medicines"].append(model_to_dict(m))
    return JsonResponse(data_dict)


def get_non_medicine(request):
    data_dict = dict()
    data_dict["nonmedicines"] = list()
    for n in Nonmedicine.objects.all():
        data_dict["nonmedicines"].append(model_to_dict(n))
    return JsonResponse(data_dict)


def get_staff(request):
    data_dict = dict()
    data_dict["staffs"] = list()
    for s in Staff.objects.all():
        data_dict["staffs"].append(model_to_dict(s))
    return JsonResponse(data_dict)

def adddoc(request):
    doc = Doctor()
    doc.name= request.POST['name']
    doc.qualification= request.POST["qualification"]
    doc.pt_ref = request.POST["pt_ref"]
    doc.reg_no = request.POST["reg_no"]
    doc.save()
    doctors = Doctor.objects.all()
    context = {'doctors': doctors, 'site': 'Our'}
    return render(request, 'pharma/doctor.html', context)

def adddocs(request):
    return render(request, 'pharma/inputdoc.html')

def addstaff(request):
    doc = Staff()
    doc.name= request.POST["name"]
    doc.age= request.POST["age"]
    doc.loc = request.POST["location"]

    doc.save()
    staffs = Staff.objects.all()
    context = {'staffs': staffs, 'site': 'Our'}
    return render(request, 'pharma/staff.html', context)

def addstaffs(request):
    return render(request, 'pharma/inputstaff.html')

def addmed(request):
    doc = Medicines()
    doc.name= request.POST['name']
    doc.exp_date= request.POST["exp_date"]
    doc.manu_date = request.POST["manu_date"]
    doc.quantity = request.POST["qty"]
    doc.price = request.POST["price"]
    doc.save()
    doctors = Medicines.objects.all()
    context = {'medicines': doctors, 'site': 'Our'}
    return render(request, 'pharma/medicine.html', context)

def addmeds(request):
    return render(request, 'pharma/inputmed.html')

def addnonmed(request):
    doc = Nonmedicine()
    doc.name= request.POST['name']
    doc.quantity= request.POST["qty"]
    doc.manu_date = request.POST["manu_date"]
    doc.price = request.POST["price"]
    doc.exp_date = request.POST["exp_date"]
    doc.save()
    doctors = Nonmedicine.objects.all()
    context = {'nonmedicines': doctors, 'site': 'Our'}
    return render(request, 'pharma/nonmedicine.html', context)

def addnonmeds(request):
    return render(request, 'pharma/inputnonmed.html')

def deldocs(request, pk):
    dmed = get_object_or_404(Doctor, pk=pk)
    temp = Doctor.objects.filter(name=dmed.name).delete()
    print temp
    doctors = Doctor.objects.all()
    context = {'doctors': doctors, 'site': 'Our'}
    return render(request, 'pharma/doctor.html', context)

def delmeds(request, pk):
    dmed = get_object_or_404(Medicines, pk=pk)
    temp = Medicines.objects.filter(name=dmed.name).delete()
    print temp
    doctors = Medicines.objects.all()
    context = {'medicines': doctors, 'site': 'Our'}
    return render(request, 'pharma/medicine.html', context)

def delnonmeds(request, pk):
    dmed = get_object_or_404(Nonmedicine, pk=pk)
    temp = Nonmedicine.objects.filter(name=dmed.name).delete()
    print temp
    doctors = Nonmedicine.objects.all()
    context = {'nonmedicines': doctors, 'site': 'Our'}
    return render(request, 'pharma/nonmedicine.html', context)

def delstaffs(request, pk):
    dmed = get_object_or_404(Staff, pk=pk)
    temp = Staff.objects.filter(name=dmed.name).delete()
    print temp
    doctors = Staff.objects.all()
    context = {'staffs': doctors, 'site': 'Our'}
    return render(request, 'pharma/staff.html', context)

pharma/templates/pharma/doctor.html
{% extends 'pharma/base_template.html' %}

{%  block body %}
<style>.change-icon > .fa + .fa,
.change-icon:hover > .fa {display: none;}
.change-icon:hover > .fa + .fa {display: inherit; cursor: pointer;}</style>
<div class="container-fluid">
</br></br></br></br>
<div class="row">
<div class="col-md-10 offset-md-1">
<div class="jumbotron-fluid">

<div class="jumbotron" style="background-color:#F5F5F5">
  <div class="container">
  <div class="btn-group" style="float:right;" role="group" aria-label="Basic example">
  <button type="button" style="color:black;"class="btn {% if site == 'Andheri' %} active {% endif %} btn-outline-secondary"><a style="text-decoration:none; color:black;" href="{% url 'pharma:dispdocs' 'Andheri' %}">Andheri</a></button>
  <button type="button" style="color:black;"class="btn {% if site == 'Kandivali' %} active {% endif %}btn btn-outline-secondary"><a style="text-decoration:none; color:black;" href="{% url 'pharma:dispdocs' 'Kandivali' %}">Kandivali</a></button>
  <button type="button" style="color:black;"class="btn btn {% if site == 'Our' %} active {% endif %}btn-outline-secondary"><a style="text-decoration:none; color:black;" href="{% url 'pharma:doctor' %}">Powai</a></button>
</div>
    <h1 class="display-4">{{ site }} Doctors</h1></br>
	<table class="table table-hover">
  <thead class="thead-default">
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Qualification</th>
      <th>Reg No.</th>
        <th>Pt Ref</th>
    </tr>
  </thead>
        {% for d in doctors %}
  <tbody>
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ d.name}}</td>
      <td>{{ d.qualification }}</td>
      <td>{{ d.reg_no }}</td>
        <td>{{ d.pt_ref }} <a href="{% url 'pharma:deldocs' d.id %}"><span style="color:red ;float:right;" class="change-icon">
            <i class="fa fa-trash-o"></i>
            <i class="fa fa-trash"></i>

        </span></a></td>
    </tr>
  </tbody>
        {% endfor %}
</table>
               </br>
  <a href="{% url 'pharma:adddocs' %}">
  <button class="btn btn-outline-primary" style="float:right;">
+
</button>
      </a>

  </div>
</div>
</div>


</br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br>.
</div>
</div>



</div>

{% endblock %}

pharma/templates/pharma/home.html
{% extends 'pharma/base_template.html' %}

{%  block body %}
<i id="abc"class="fa fa-heartbeat" style="font-size:250px;position:absolute;right:42%;top:30%;color:#B71C1C;"></i>

{% endblock %}

pharma/templates/pharma/inputdoc.html
{% extends 'pharma/base_template.html' %}

{%  block body %}

</br></br></br>
        <div class="container-fluid">

            <div class="row">

                <div class="col-md-8 offset-md-2">
                    <div class="jumbotron">

                        <form action="{% url 'pharma:adddoc' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
<h6 class="display-4">Enter Details</h6>

<div class="form-group row">
  <label for="name" class="col-2 col-form-label">Name</label>
  <div class="col-10">
    <input class="form-control" type="text" value="Ar kale" id="name" name="name">
  </div>
</div>
<div class="form-group row">
  <label for="qualification" class="col-2 col-form-label">Qualification</label>
  <div class="col-10">
    <input class="form-control" type="search" value="MBBS" id="qualification" name="qualification">
  </div>
</div>
<div class="form-group row">
  <label for="reg_no" class="col-2 col-form-label">Reg No</label>
  <div class="col-10">
    <input class="form-control" type="text"  id="reg_no" name="reg_no">
  </div>
</div>
<div class="form-group row">
  <label for="pt_ref" class="col-2 col-form-label">Pt Ref</label>
  <div class="col-10">
    <input class="form-control" type="text"  id="pt_ref" name="pt_ref">
  </div>
</div>
 <div class="form-group row" align="center">
     <button type="submit" class="btn btn-default">Submit</button>
 </div>
                            </form>

                </div>
            </div>
            </div>

{% endblock %}

pharma/templates/pharma/inputmed.html
{% extends 'pharma/base_template.html' %}

{%  block body %}
</br></br></br>

    <div class="container-fluid">

            <div class="row">

                <div class="col-md-8 offset-md-2">
                    <div class="jumbotron">
    <form role="form" action="{% url 'pharma:addmed' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
<h6 class="display-4">Enter Details</h6>

<div class="form-group row">
  <label for="name" class="col-2 col-form-label">Name</label>
  <div class="col-10">
    <input class="form-control" type="text"  id="name" name="name">
  </div>
</div>
<div class="form-group row">
  <label for="qualification" class="col-2 col-form-label">Manufacture</label>
  <div class="col-10">
    <input class="form-control" type="text"  id="manu_date" name="manu_date">
  </div>
</div>
<div class="form-group row">
  <label for="composition" class="col-2 col-form-label">Composition</label>
  <div class="col-10">
    <input class="form-control" type="text"  id="composition" name="composition">
  </div>
</div>
<div class="form-group row">
  <label for="expiry" class="col-2 col-form-label">Expiry</label>
  <div class="col-10">
    <input class="form-control" type="text"  id="expiry" name="exp_date">
  </div>
</div>
<div class="form-group row">
  <label for="price" class="col-2 col-form-label">Price</label>
  <div class="col-10">
    <input class="form-control" type="text"  id="price" name="price">
  </div>
</div>
<div class="form-group row">
  <label for="qty" class="col-2 col-form-label">Qty</label>
  <div class="col-10">
    <input class="form-control" type="text"  id="qty" name="qty">
  </div>
</div>
    <div class="form-group row" align="center">
     <button type="submit" class="btn btn-default">Submit</button>
 </div>
    </form>


{% endblock %}

pharma/templates/pharma/inputnonmed.html
{% extends 'pharma/base_template.html' %}

{%  block body %}
</br></br></br>

    <div class="container-fluid">

            <div class="row">

                <div class="col-md-8 offset-md-2">
                    <div class="jumbotron">
<form role="form" action="{% url 'pharma:addnonmed' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
<h6 class="display-4">Enter Details</h6>

<div class="form-group row">
  <label for="name" class="col-2 col-form-label">Name</label>
  <div class="col-10">
    <input class="form-control" type="text"  id="name" name="name">
  </div>
</div>
<div class="form-group row">
  <label for="qualification" class="col-2 col-form-label">Manufacture</label>
  <div class="col-10">
    <input class="form-control" type="text"  id="manu_date" name="manu_date">
  </div>
</div>

<div class="form-group row">
  <label for="expiry" class="col-2 col-form-label">Expiry</label>
  <div class="col-10">
    <input class="form-control" type="text"  id="expiry" name="exp_date">
  </div>
</div>
<div class="form-group row">
  <label for="price" class="col-2 col-form-label">Price</label>
  <div class="col-10">
    <input class="form-control" type="text"  id="price" name="price">
  </div>
</div>
<div class="form-group row">
  <label for="qty" class="col-2 col-form-label">Qty</label>
  <div class="col-10">
    <input class="form-control" type="text"  id="qty" name="qty">
  </div>
</div>
    <div class="form-group row" align="center">
     <button type="submit" class="btn btn-default">Submit</button>
 </div>
    </form>

{% endblock %}

pharma/templates/pharma/inputstaff.html
{% extends 'pharma/base_template.html' %}

{%  block body %}
</br></br></br>
    <div class="container-fluid">

            <div class="row">

                <div class="col-md-8 offset-md-2">
                    <div class="jumbotron">

    <form role="form" action="{% url 'pharma:addstaff' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

<h6 class="display-4">Enter Details</h6>
<div class="form-group row">
  <label for="name" class="col-2 col-form-label">Name</label>
  <div class="col-10">
    <input class="form-control" type="text"  id="name" name="name">
  </div>
</div>
<div class="form-group row">
  <label for="Age" class="col-2 col-form-label">Age</label>
  <div class="col-10">
    <input class="form-control" type="text"  id="Age" name="age">
  </div>
</div>
<div class="form-group row">
  <label for="location" class="col-2 col-form-label">Location</label>
  <div class="col-10">
    <input class="form-control" type="text" value="powai" id="location" name="location">
  </div>
</div>
    <div class="form-group row" align="center">
     <button type="submit" class="btn btn-default">Submit</button>
 </div>
    </form>



{% endblock %}

pharma/templates/pharma/medicine.html
{% extends 'pharma/base_template.html' %}

{%  block body %}
<style>.change-icon > .fa + .fa,
.change-icon:hover > .fa {display: none;}
.change-icon:hover > .fa + .fa {display: inherit; cursor: pointer;}</style>
<div class="container-fluid">
</br></br></br></br>
<div class="row">
<div class="col-md-10 offset-md-1">
<div class="jumbotron-fluid">

<div class="jumbotron" style="background-color:#F5F5F5">
  <div class="container">
  <div class="btn-group" style="float:right;" role="group" aria-label="Basic example">
  <button type="button" style="color:black;"class="btn {% if site == 'Andheri' %} active {% endif %} btn-outline-secondary"><a style="text-decoration:none; color:black;"href="{% url 'pharma:dispmeds' 'Andheri' %}">Andheri</a></button>
  <button type="button" style="color:black;"class="btn {% if site == 'Kandivali' %} active {% endif %}btn btn-outline-secondary"><a style="text-decoration:none; color:black;"href="{% url 'pharma:dispmeds' 'Kandivali' %}">Kandivali</a></button>
  <button type="button" style="color:black;"class="btn btn {% if site == 'Our' %} active {% endif %}btn-outline-secondary"><a style="text-decoration:none; color:black;"href="{% url 'pharma:medicine' %}">Powai</a></button>
</div>
    <h1 class="display-4">{{ site }} Medicine</h1></br>
	<table class="table table-hover">
  <thead class="thead-default">
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Composition</th>
      <th>Manufacture</th>
      <th>Expiry</th>
      <th>Price</th>
      <th>Quantity</th>
    </tr>
  </thead>
        {% for m in medicines %}
  <tbody>
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ m.name}}</td>
      <td>{{ m.composition}}</td>
      <td>{{ m.manu_date }}</td>
      <td>{{ m.exp_date }}</td>
      <td>{{ m.price }}</td>
      <td>{{ m.quantity }}<a href="{% url 'pharma:delmeds' m.id %}"><span style="color:red ;float:right;" class="change-icon">
            <i class="fa fa-trash-o"></i>
            <i class="fa fa-trash"></i>

        </span></a></td>
    </tr>
  </tbody>
        {% endfor %}
</table></br>
  <a href="{% url 'pharma:addmeds' %}">
  <button class="btn btn-outline-primary" style="float:right;">
+
</button>
      </a>
  </div>
</div>
</div>

</br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br>.
</div>
</div>



</div>

{% endblock %}

pharma/templates/pharma/nonmedicine.html
{% extends 'pharma/base_template.html' %}

{%  block body %}
<style>.change-icon > .fa + .fa,
.change-icon:hover > .fa {display: none;}
.change-icon:hover > .fa + .fa {display: inherit; cursor: pointer;}</style>
<div class="container-fluid">
</br></br></br></br>
<div class="row">
<div class="col-md-10 offset-md-1">
<div class="jumbotron-fluid">

<div class="jumbotron" style="background-color:#F5F5F5">
  <div class="container">
  <div class="btn-group" style="float:right;" role="group" aria-label="Basic example">
    <button type="button" style="color:black;"class="btn {% if site == 'Andheri' %} active {% endif %} btn-outline-secondary"><a style="text-decoration:none; color:black;"href="{% url 'pharma:dispnonmeds' 'Andheri' %}">Andheri</a></button>
    <button type="button" style="color:black;"class="btn {% if site == 'Kandivali' %} active {% endif %}btn btn-outline-secondary"><a style="text-decoration:none; color:black;"href="{% url 'pharma:dispnonmeds' 'Kandivali' %}">Kandivali</a></button>
    <button type="button" style="color:black;"class="btn btn {% if site == 'Our' %} active {% endif %}btn-outline-secondary"><a style="text-decoration:none; color:black;"href="{% url 'pharma:nonmedicine' %}">Powai</a></button>
</div>
    <h1 class="display-4">{{ site }} Non Medicine</h1></br>
	<table class="table table-hover">
  <thead class="thead-default">
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Manufacture</th>
      <th>Expiry</th>
      <th>Price</th>
      <th>Quantity</th>
    </tr>
  </thead>
        {% for nm in nonmedicines %}
  <tbody>
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ nm.name}}</td>
      <td>{{ nm.manu_date }}</td>
      <td>{{ nm.exp_date }}</td>
      <td>{{ nm.price }}</td>
      <td>{{ nm.quantity }} <a href="{% url 'pharma:delnonmeds' nm.id %}"><span style="color:red ;float:right;" class="change-icon">
            <i class="fa fa-trash-o"></i>
            <i class="fa fa-trash"></i>

        </span></a></td>
    </tr>
  </tbody>
        {% endfor %}
</table>

 </br>
  <a href="{% url 'pharma:addnonmeds' %}">
  <button class="btn btn-outline-primary" style="float:right;">
+
</button>
      </a>

  </div>
</div>
</div>

</br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br>.
</div>
</div>



</div>

{% endblock %}

pharma/templates/pharma/staff.html
{% extends 'pharma/base_template.html' %}

{%  block body %}
<style>.change-icon > .fa + .fa,
.change-icon:hover > .fa {display: none;}
.change-icon:hover > .fa + .fa {display: inherit; cursor: pointer;}</style>
<div class="container-fluid">
</br></br></br></br>
<div class="row">
<div class="col-md-10 offset-md-1">
<div class="jumbotron-fluid">

<div class="jumbotron" style="background-color:#F5F5F5">
  <div class="container">
  <div class="btn-group" style="float:right;" role="group" aria-label="Basic example">
  <button type="button" style="color:black;"class="btn {% if site == 'Andheri' %} active {% endif %} btn-outline-secondary"><a style="text-decoration:none; color:black;"href="{% url 'pharma:dispstaff' 'Andheri' %}">Andheri</a></button>
  <button type="button" style="color:black;"class="btn {% if site == 'Kandivali' %} active {% endif %}btn btn-outline-secondary"><a style="text-decoration:none; color:black;"href="{% url 'pharma:dispstaff' 'Kandivali' %}">Kandivali</a></button>
  <button type="button" style="color:black;"class="btn btn {% if site == 'Our' %} active {% endif %}btn-outline-secondary"><a style="text-decoration:none; color:black;"href="{% url 'pharma:staff' %}">Powai</a></button>
</div>
    <h1 class="display-4">{{ site }} Staff</h1></br>
	<table class="table table-hover">
  <thead class="thead-default">
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Age</th>
      <th>Location</th>
    </tr>
  </thead>
        {% for s in staffs %}
  <tbody>
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ s.name}}</td>
      <td>{{ s.age }}</td>
      <td>{{ s.loc }}
      <a href="{% url 'pharma:delstaffs' s.id %}"><span style="color:red ;float:right;" class="change-icon">
            <i class="fa fa-trash-o"></i>
            <i class="fa fa-trash"></i>

        </span></a></td>
    </tr>
  </tbody>
        {% endfor %}
</table>
</br>
  <a href="{% url 'pharma:addstaffs' %}">
  <button class="btn btn-outline-primary" style="float:right;">
+
</button>
      </a>

  </div>
</div>
</div>
</br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br>.
</div>
</div>



</div>

{% endblock %}